### ISSUE TITLE
Missing order classes in function col

### ISSUE THREAD

**Issue by neverin772** [tuxnull/BootstraPHP#11]
**Describe the bug**
Col function is missing the ability to change the order of cols based on class.

order-*
order-sm-*
order-md-*

https://getbootstrap.com/docs/4.0/layout/grid/#order-classes

**Comment by tuxnull** [comment]
What do you mean?

You can set multiple classes in a col
e.g:
array("col-sm"=>"6","col-md"=>"8")

**Comment by neverin772** [comment]
col-sm sets the size, order classes set the order so you can do this: - 

Div 1 - first
Div 2 - second

on mobile - 

Div 2 - First
Div 1 - Second

**Comment by tuxnull** [comment]
Ah. Will look into it

**Comment by tuxnull** [comment]
Done!
