### ISSUE TITLE
Pass vars from an array

### ISSUE THREAD

**Issue by neverin772** [tuxnull/BootstraPHP#2]
Curious, would it not be better  when an element has a large number of options e.g.

custom_link($element, $links_to, $content, $style, $disabled)

as an array like: - 

```
$args = array('I contain' => 'all the options');
echo custom_link($links_to, $args);
```
 That way when working with lots of custom_links you have one central place to control them?

**Comment by tuxnull** [comment]
Good idea! 
Will probably implement it with Version 0.1.0.
Thanks for the suggestion!

**Comment by neverin772** [comment]
If it's possible I'd like to help with this, I work with bootstrap/php a lot so if possible I might submit some code later to help.

**Comment by tuxnull** [comment]
That would be awesome. Feel free to open a pull request whenever you like :-P

**Comment by tuxnull** [comment]
I've already started work on 0.1.0 and have created a 0.1.0 branch. Please make sure to choose the 0.1.0 branch as base for your pull request.
